const descrition = {
    normal: 'Esses pokemons são seguidores e mudam sua personalidade para caber na multidão. Eles evitam ser diferentes como a peste e se sentem acima de tais bobagens. Eles, como a normalidade, são falsos em suas crenças e escondem suas próprias idiossincrasias dos outros com medo de reação.',
	fire: 'Esses pokemons são muito apaixonadas pelo que pensam / fazem. Eles permanecem dedicados e fazem o trabalho. Eles são empreendedores e continuarão bebendo ao longo do dia. Eles, como o fogo, continuarão tentando acender até que sua energia acabe.',
	water: 'Esses pokemons são do tipo que segue o fluxo. Eles são muito flexíveis na gestão do tempo e têm uma personalidade despreocupada, que estará aberta a qualquer atividade que surja em seu caminho. Eles, como a água, vão aonde a maré os levar.',
	electric: 'Esses pokemons são muito extrovertidas e emitem muita energia. Eles são espontâneos e extrovertidos. Eles geralmente são o centro das atenções em qualquer reunião social. Eles adoram ser seu próprio mascote. Eles, como a eletricidade, podem iluminar a sala, desde que haja uma tomada para eles.',
	grass: 'Esses pokemons são muito introvertidas em seu pensamento e geralmente gostam de estar com elas mesmas. Eles estão muito em contato com o meio ambiente e confiam no que os rodeia na vida. Eles são confiáveis ​​em relacionamentos um a um. Eles, como a grama, permanecem firmes e sempre podem florescer quando chegar a hora certa.',
	ice: 'É muito difícil fazer amizade com esses pokemons no início, pois são rudes nas bordas. Eles geralmente continuam a construir um muro de reclusão e fugir dos problemas. Eles, como o gelo, podem congelar em certas situações, mas se você se aquecer com eles, eles podem simplesmente derreter.',
	fighting: 'Esses pokemons adoram debater sempre que possível. Eles amam a competição, uma vez que os desafia como nenhum outro. Quando estão com raiva, eles podem atacar de forma agressiva. Porém, eles, assim como os lutadores, têm uma rotina na academia que os mantém centrados e à vontade com a vida quando precisam de sossego.',
	poison: 'Esses pokemons continuam a machucar outras quando não é essa a intenção. Há uma nuvem cinza entre eles que pode prejudicar aqueles que os cercam. Eles, como o veneno, podem ser muito tóxicos nos relacionamentos e precisam de um antídoto, ou cura, para remover sua negatividade.',
	ground: 'Esses pokemons são muito tradicionais em seus valores e têm dificuldade em mudar. Freqüentemente, são teimosos e gostam de seguir o que sabem. Isso pode impactar seu aprendizado, pois eles podem não ter a mente mais aberta. Eles, como o solo, são duros até o âmago, mas estão sempre lá quando você cai.',
	flying: 'Esses pokemons são sonhadoras e adoram atirar para o céu. Eles não gostam de ficar no mesmo lugar por muito tempo. Eles desejam realizar seu sonho em vários locais. Eles, como os pássaros, valorizam a viagem como uma experiência que se torna natural para eles.',
	psychic: 'Esses pokemons predizem o futuro e geralmente têm um bom juiz de caráter. Eles parecem ser superinteligentes e confiam em seu cérebro para levá-los longe na vida. Eles também são muito espirituais e podem usar auras para tomar decisões. Eles, como os médiuns, procuram entender as outras pessoas, pois isso lhes dá uma ideia de como as pessoas reagem.',
	bug: 'Esses pokemons são os oprimidos que estão entrando na vida. Eles são continuamente subestimados e não considerados grandes ameaças em qualquer situação. Eles, como os insetos, geralmente são pisados ​​na vida, mas se conseguirem ganhar coragem para evoluir para algo maior, haverá esperança para sua existência.',
	rock: 'Esses pokemons são muito obstinadas / obstinadas. Freqüentemente, são muito independentes e acreditam que podem arrasar pela vida sem se importar com o mundo. Eles, como pedras, são difíceis de invadir, a menos que você tenha as ferramentas certas para iniciar uma conversa.',
	ghost: 'Esses pokemons adoram manter as pessoas alerta. Eles são brincalhões e adoram torturar outras pessoas quando o tempo permite. Você nunca sabe o que está acontecendo. Eles, como fantasmas, amam espreitar nas sombras, impactando os outros à distância.',
	dragon: 'Esses pokemons são empreendedoras e pensam que podem fazer tudo. Muitas vezes as pessoas superestimam a eles e a suas habilidades e, se forem decepcionadas, isso pode realmente afetar seu ego. Eles, como os dragões, são rápidos e poderosos, mas também podem liberar muito vapor, ferindo outras pessoas no processo.',
	dark: 'Esses pokemons ficam escondidas até que realmente conheçam alguém. Eles manterão uma fachada tranquila e só revelarão seu passado quando o tempo permitir. Eles, como a escuridão, gostam de evitar a luz e se vestem de preto sempre que possível.',
	steel: 'Esses pokemons são muito diretas e voltadas para um objetivo. Sua franqueza pode ser prejudicada às vezes quando outros estão ao redor. Eles, como o aço, têm momentos brilhantes e podem realmente ajudar a construir suas próprias vidas quando seus objetivos se alinham como tais.',
	fairy: 'These people are the new people in the crowd. They are optimistic and very colorful. They, like fairies, are cheery and preppy, and will inevitably have their wings pulled when they eventually start the unnerving part of reality. ',
};
// @ts-ignore
const getDescription = (type: string): string => descrition[type] || '';
export default getDescription;